### ISSUE TITLE
how to handle error at custom logic authentication

### ISSUE THREAD

**Issue by dearpeach** [mbell8903/passport-custom#12]
if a error returned at CustomStrategy ,
it didn't traggle the failureRedirect setting,
how to handle it and displayed it?

thank you guys

**Comment by shaozi** [comment]
I ran into the same issue. Seems a bug to me.

**Comment by shaozi** [comment]
One can use the `Custom Callback` method to handle the post result, as in the [Custom Callback](http://www.passportjs.org/docs/) section. This way, you have complete control on redirect.

```javascript
app.post('/login', function(req, res, next) {
  passport.authenticate('local', function(err, user, info) {
    if (err) { return next(err); }
    if (!user) { return res.redirect('/login'); }
    req.logIn(user, function(err) {
      if (err) { return next(err); }
      return res.redirect('/users/' + user.username);
    });
  })(req, res, next);
});
```
