### ISSUE TITLE
Does this work for multiple strategies?

### ISSUE THREAD

**Issue by dalepo** [mbell8903/passport-custom#16]
Currently trying:
```
passport.authenticate([
    'basic', 'my-custom-strategy', 'oauth2-client-password'
    ], {session: false}
),
```
This bypasses the first strategy and goes directly to my-custom-strategy. The flow continues to oauth2 just fine, but 'basic' never triggers.

**Comment by mbell8903** [comment]
That’s because the basic strategy is failing to find the appropriate HTTP headers to trigger the strategy.  That or the basic strategy has not be registered under that name when passport initializes.  Check the latter first, then the former.

**Comment by dalepo** [comment]
Thank you @mbell8903 
Will close this.
