### ISSUE TITLE
README.md link to examples is broken

### ISSUE THREAD

**Issue by dannylevenson-ps** [mbell8903/passport-custom#2]
When I click on the examples link in your readme (https://github.com/mbell8903/passport-custom/tree/master/examples) I get a 404.  Please fix this link so that I can see your examples.

**Comment by mattidupre** [comment]
This is pretty much all there is to it. Note that, ```req``` is always passed as the first parameter to the authorization callback.

```javascript

passport.use('strategy-name', new CustomStrategy(
  function(req, callback) {
    // build user or set to false based on req object
    callback(null, user);
  }
));

```

**Comment by mbell8903** [comment]
Example section removed since there are tons of examples on the internet on how to use passport strategies.  The code sample referenced by @mattidupre is good enough.

**Comment by shawn-simon** [comment]
the example is wrong ffs

**Comment by angelxmoreno** [comment]
The least we can do for the author is submit a PR FFS :stuck_out_tongue_closed_eyes:
