### ISSUE TITLE
wrong parameters in the example code

### ISSUE THREAD

**Issue by kesav02** [mbell8903/passport-custom#6]
Hey,

Thanks for this lovely and helpful package :)
If I am not wrong, you need to fix the 2nd line on the example below.
"function(done) {" should be "function(req, done) {"
you could also add console.log(req.body.username) to make other understand it better

passport.use('custom', new CustomStrategy(
  function(done) {
    User.findOne({ uid: 1 }, function (err, user) {
      if (err) { return done(err); }
      if (!user) { return done(null, false); }
      return done(null, user);
    });
  }
));

**Comment by JamesMGreene** [comment]
:+1:
