### ISSUE TITLE
Submit PR to add this Strategy to passportjs.org website

### ISSUE THREAD

**Issue by JamesMGreene** [mbell8903/passport-custom#7]
If you want your "passport-custom" strategy to be listed/searchable on the passportjs.org website, you can submit a PR to the repo https://github.com/passport/www.passportjs.org in which you add your strategy info into the `strategies.yaml` file.

**Comment by mbell8903** [comment]
Pull request made: https://github.com/passport/www.passportjs.org/pull/43

**Comment by JamesMGreene** [comment]
Thanks!
