### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by rutkowskib** [mbell8903/passport-custom#9]
Hi,

I would like to add Typescript definitions to this library. Would you be interested in pulling it when I'm finished?

**Comment by vschoener** [comment]
@rutkowskib Did you do something about it? :)

**Comment by mbell8903** [comment]
@vschoener No pull request was made yet, however if you'd like to implement I'll review and pull in.

**Comment by Scalpel78** [comment]
I'm also interrested in typescript support.

**Comment by schmollmolch** [comment]
Looking for ts as well. Apparently @rutkowskib added types in his fork but did not open a pull request. Are there any issues with just merging these changes?
https://github.com/mbell8903/passport-custom/compare/master...rutkowskib:master

**Comment by rutkowskib** [comment]
I completely forgot about this. I created PR now so you can merge it if you want. I used it a long time ago so it might be outdated though
